spring:
  application:
    name: food-ordering-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/foodorderingdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret

axon:
#  serializer:
#    general: jackson
  kafka:
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    default-topic: axon.events
#    properties:
#      security.protocol: PLAINTEXT
#    fetcher:
#      poll-timeout: 3000
    consumer:
      group-id: ${spring.application.name}-group
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking
  eventhandling:
    processors:
      kafka-axon-event-processor:
        source: kafkaMessageSource
        mode: tracking

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC